services:
  app-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - AWS_ACCESS_KEY_ID=${aws_access_key_id}
      - AWS_SECRET_ACCESS_KEY=${aws_secret_access_key}
    volumes:
      - ./temp/reports:/usr/src/app/temp/reports
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    networks:
      - app-upload-certificates  # Está en la red correcta
  
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-backend
    networks:
      - app-upload-certificates
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

networks:
  app-upload-certificates:
    external: true